# Generated by Django 5.0.1 on 2024-01-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.transferlist')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerBuy',
        ),
    ]
