# Generated by Django 5.0.1 on 2024-01-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_buyplayer_delete_playerbuy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyPlayer',
        ),
    ]
